### Criar produto
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Abacaxi Pérola",
  "price": 7.99,
  "featured": true,
  "category": "Frutas",
  "image": "https://cdn.example.com/abacaxi.jpg",
  "userLikePercentage": 87,
  "marketId": 1
}

###

### Buscar todos os produtos
GET http://localhost:3000/products

###

### Buscar produtos por categoria (Frutas)
GET http://localhost:3000/products?category=Frutas

###

### Buscar produtos em destaque
GET http://localhost:3000/products/featured

###

### Verificar se um produto está favoritado (substitua TOKEN e ID do produto)
GET http://localhost:3000/products/favorites/1
Authorization: Bearer {{TOKEN}}

###

### Alternar like (favoritar/desfavoritar)
PATCH http://localhost:3000/products/1/like
Authorization: Bearer {{TOKEN}}

###

### Buscar produtos favoritados pelo usuário logado
GET http://localhost:3000/products/favorites
Authorization: Bearer {{TOKEN}}

###

### Buscar produto por ID
GET http://localhost:3000/products/1
